Updates requests and urllib3 requirements
freedomofpress/securedrop-client pull request #1155
Opened 2020-10-08 02:39 UTC by zenmonkeykstop

# Description

Updates urllib3 dependency from 1.25.8 to 1.25.10 (and requests from 2.20.0 to 2.22.0) to pass safety check.

# Test Plan

- [ ] does CI pass?

2020-10-08 21:17 UTC, emkll requested changes
`build-requirements.txt` is in the `requirements/` directory and not the repo root for this repo.

2020-10-13 17:04 UTC, emkll commented
Rebased on latest main

2020-10-13 21:29 UTC, creviera requested changes
looks good - just need to update requirements/dev-mac-requirements.txt

2020-10-15 14:20 UTC, zenmonkeykstop commented on requirements/build-requirements.txt
> +requests==2.22.0 --hash=sha256:e3711bd465fd013abe428a8dade2938b578f05d2b06b0ae83daa98869c4548e8
OK, macOS build reqs updated.

2020-10-15 16:09 UTC, creviera approved these changes
lgtm!

2020-10-15 16:11 UTC, merged