Cancel old GHA builds if new commits are pushed
freedomofpress/securedrop-client pull request #1864
Opened 2024-02-22 22:08 UTC by legoktm

## Status

Ready for review

## Description

Reduces the queue size when refactoring or quickly pushing new things.
This is roughly the same behavior CircleCI had.
    
Inspired by <https://stackoverflow.com/questions/68418857/how-to-cancel-existing-runs-when-a-new-push-happens-on-github-actions-but-only>.
    
Fixes #1858.

## Test Plan

* [ ] When I force pushed onto this branch, it cancelled the in-progress jobs (see screenshot)
* [ ] Feel free to amend/push to this PR for further testing
![Screenshot 2024-02-22 at 17-07-27 Workflow runs · freedomofpress_securedrop-client](https://github.com/freedomofpress/securedrop-client/assets/81392/ff946ad4-c85c-40b0-ba4f-c08a06103bbb)

2024-02-23 01:15 UTC, legoktm commented on .github/workflows/build.yml
> +  cancel-in-progress: ${{ github.ref != 'refs/heads/main' || startsWith( github.ref, 'refs/heads/release/' ) }}
@rocodes pointed out that this logic is wrong, I think it should be `&& !startsWith(...)`

2024-02-29 18:50 UTC, legoktm commented on .github/workflows/build.yml
> +  cancel-in-progress: ${{ github.ref != 'refs/heads/main' || startsWith( github.ref, 'refs/heads/release/' ) }}
Fixed and documented the expected logic in the commit message / PR description

2024-03-04 18:20 UTC, rocodes commented
Okay, so there may still be a quirk in here @legoktm:  I tested this PR by checking out another branch from the tip of this branch, cause I didn't want to mess with your commit signing. (see `ro-tests-faster-builds` branch).  I then committed, pushed, hard reset to  https://github.com/freedomofpress/securedrop-client/commit/f9ddf7168ec461788961354c69824bc0fc5e5cb1, and re-pushed, all on my own branch, and .... it re-triggers CI on this branch too. :upside_down_face:  Cause of the way we are using the github ref.

2024-03-04 18:23 UTC, rocodes requested changes
See https://github.com/freedomofpress/securedrop-client/pull/1864#issuecomment-1977193109

2024-03-04 18:24 UTC, legoktm commented
I think you should see that behavior on any PR - GitHub stores the status of checks on the latest commit of a PR (rather than the PR itself), so pushing a commit to a branch will re-trigger CI, and that is reflected across the board on any PRs. (I've used this trick a few times to push to a stg- branch in the server repo, and then that staging job will show up in the PR report even though it's not on that branch.) It's definitely weird and non-intuitive though.

2024-03-04 18:30 UTC, rocodes commented
Hm. It does seem odd/ uncomfortable that another branch can retrigger CI for a different branch. But if it's not a change in behaviour I guess I will have another coffee and adjust my understanding of the world ;)

2024-03-04 18:36 UTC, rocodes approved these changes
Per https://github.com/freedomofpress/securedrop-client/pull/1864#issuecomment-1977198709, approving. Successful cancellation of in-progress builds in my testing, and retriggering builds against same hash is expected.

2024-03-04 18:36 UTC, merged