Find all securedrop-client packages in (client) setup.py; fix securedrop-export postrm
freedomofpress/securedrop-client pull request #1873
Opened 2024-02-27 00:47 UTC by rocodes

## Status

Ready for review

## Description

After #1854 and #1844, there were two issues with building packages.  
- `securedrop-export` built successfully, but when installing, postrm generated an error due to not being POSIX compliant
- `securedrop-client` built "successfully" but a number of packages were missing. This was confusing until @cfm pointed me at setup.py, noticing that it specifies packages by name, and does not include all the packages. `MANIFEST.in` was filling that gap for us, which probably wasn't intentional.   

## Test Plan
- [ ] Visual review
- [ ] CI passing
- [ ] `.scripts/build-deb.sh` and smoketest (packages install and launch successfully)

## Checklist

If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging environment is required. For fine tuning of the graphical user interface, testing in any environment in Qubes is required. Please check as applicable:

 - [ ] I have tested these changes in the appropriate Qubes environment
 - [ ] I do not have an appropriate Qubes OS workstation set up (the reviewer will need to test these changes)
 - [x] These changes should not need testing in Qubes

If these changes add or remove files other than client code, the AppArmor profile may need to be updated. Please check as applicable:

 - [ ] I have updated the [AppArmor profile](https://github.com/freedomofpress/securedrop-client/blob/HEAD/files/usr.bin.securedrop-client)
 - [x] No update to the AppArmor profile is required for these changes
 - [ ] I don't know and would appreciate guidance

If these changes modify the database schema, you should include a database migration. Please check as applicable:

 - [ ] I have written a migration and upgraded a test database based on `main` and confirmed that the migration is [self-contained] and applies cleanly
 - [ ] I have written a migration but have not upgraded a test database based on `main` and would like the reviewer to do so
 - [ ] I need help writing a database migration
 - [x] No database schema changes are needed

[self-contained]: https://github.com/freedomofpress/securedrop-client#generating-and-running-database-migrations

2024-02-27 00:49 UTC, rocodes commented
(Building packages myself now)

2024-02-27 01:13 UTC, rocodes commented
This will be a little more complicated than just the above change: we need to make sure that all of the data we need (resources, fonts, css files, maybe alembic files?) are included in the right places. setup.py has an option to specify `package_data` that we can use, but lots of edge case testing will still be required, or we should revert the removal of MANIFEST.in for the client component only if we're concerned about getting moving on release things.

2024-02-28 18:15 UTC, legoktm commented
For the postrm, should we switch to just having the shebang explicitly be `bash`? I think we get no advantage from using dash/"sh".

2024-02-28 23:37 UTC, legoktm requested changes
Thanks for diagnosing these errors, overall LGTM and an improvement, see inline comments.

2024-02-28 23:37 UTC, legoktm commented on client/setup.py
> +    package_data={
I think we can skip this part if we keep the MANIFEST.in? (Also not all the CSS is in resources/, we'd need some `**/*.css` I think.

2024-02-29 15:36 UTC, rocodes commented
Yup, fine with switching to bash, was just trying to do the thing that kept our packaging the most "vanilla" while you were out ;) on it!

2024-02-29 18:39 UTC, legoktm approved these changes
LGTM, thanks!

2024-02-29 18:39 UTC, merged